### ISSUE TITLE
Not compatible with biome soawn point and village spawn point

### ISSUE THREAD

**Issue by Darklight-007** [Dekunutter/eastwardjourneys#8] opened 2023-08-31 06:36 UTC

**Comment by Darklight-007** [comment] 2023-08-31 06:36
selects other villages

**Comment by Dekunutter** [comment] 2023-09-02 04:09
Biome spawn point seems to work fine with Eastward Journeys. I was able to configure it to spawn me in the modded biomes just fine. Village spawn point doesn't seem to have any configuration to determine which villages to utilize. Since it will always use the nearest village, that's going to be pot-luck if you get the modded village or not.

I confirmed that the cherry blossom villages are indeed spawning in the world correctly, so there is no issue with them loading. They are just rare.

As such, I don't think this is an incompatibility issue - just that the cherry blossom villages are rare. Going to close this out as I don't think this is any issue with Eastward Journeys.

**Closed as completed by Dekunutter** 2023-09-02 04:09 UTC
